name: Main
main: me.mipcraft.Main
version: 1.0
softdepend: [LibsDisguises]
softdepend: [Multiverse-Core]
commands:
   spl:
      description: It tells you about the plugin.
      usage: /<command>
   splatoon:
      description: It tells you about the plugin.
      usage: /<command>
   miptoon:
      description: It tells you about the plugin.
      usage: /<command>  